sdm-845: TEMP: Get rid of bootctrl
I know, not practical, we are missing dependencies on some point:

error: device/oneplus/sdm845-common/gpt-utils/Android.bp:18:1: dependency "generated_kernel_headers" of "libgptutils.oneplus_sdm845" missing variant:
  arch:android_arm64_armv8-a, image:recovery
available variants:
  arch:android_arm64_armv8-a, image:core, version:
  arch:android_arm64_armv8-a, image:vendor, version:
  arch:android_arm_armv8-a, image:core, version:
  arch:android_arm_armv8-a, image:vendor, version:
14:42:41 soong bootstrap failed with: exit status 1

So better keep fixing other stuffses instead loosing time on this mess.